spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batchs
    username: root
    password: wevioo
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
        properties:
            hibernate:
                ddl-auto: update
                dialect: org.hibernate.dialect.MySQL5Dialect
                show_sql: true
                use_sql_comments: true
                spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect
                spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
                format_sql: true             
server:
  port: 8089