package com.nordnet.batchs.entities;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name = "batch")
public class Batch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Project project;
	private String name;
	private String url;
	private String httpVerb;
	private String description;
	private String parameters;
	private Set<BatchJobExecution> batchJobExecutions = new HashSet<BatchJobExecution>(0);

	public Batch() {
	}

	public Batch(Project project, String name, String url) {
		this.project = project;
		this.name = name;
		this.url = url;
	}

	public Batch(Project project, String name, String url, String httpVerb, String description, String parameters,
			Set<BatchJobExecution> batchJobExecutions) {
		this.project = project;
		this.name = name;
		this.url = url;
		this.httpVerb = httpVerb;
		this.description = description;
		this.parameters = parameters;
		this.batchJobExecutions = batchJobExecutions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Cascade({ CascadeType.SAVE_UPDATE })
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "http_verb", length = 45)
	public String getHttpVerb() {
		return this.httpVerb;
	}

	public void setHttpVerb(String httpVerb) {
		this.httpVerb = httpVerb;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "parameters")
	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	@Cascade({ CascadeType.DELETE })
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batch")
	public Set<BatchJobExecution> getBatchJobExecutions() {
		return this.batchJobExecutions;
	}

	public void setBatchJobExecutions(Set<BatchJobExecution> batchJobExecutions) {
		this.batchJobExecutions = batchJobExecutions;
	}

}
