package com.nordnet.batchs.entities;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 24 mars 2017 10:30:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Property generated by hbm2java
 */
@Entity
@Table(name = "property")
public class Property implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Bean beanByRef;
	private Bean beanByBeanId;
	private String name;
	private String value;

	public Property() {
	}

	public Property(String name) {
		this.name = name;
	}

	public Property(Bean beanByRef, Bean beanByBeanId, String name, String value) {
		this.beanByRef = beanByRef;
		this.beanByBeanId = beanByBeanId;
		this.name = name;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref")
	public Bean getBeanByRef() {
		return this.beanByRef;
	}

	public void setBeanByRef(Bean beanByRef) {
		this.beanByRef = beanByRef;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bean_id")
	public Bean getBeanByBeanId() {
		return this.beanByBeanId;
	}

	public void setBeanByBeanId(Bean beanByBeanId) {
		this.beanByBeanId = beanByBeanId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
