package com.nordnet.batchs.entities;

// Generated 24 mars 2017 10:30:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tasklet generated by hbm2java
 */
@Entity
@Table(name = "tasklet")
public class Tasklet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Bean bean;
	private Chunk chunk;
	private Set<Step> steps = new HashSet<Step>(0);

	public Tasklet() {
	}

	public Tasklet(int id) {
		this.id = id;
	}

	public Tasklet(int id, Bean bean, Chunk chunk, Set<Step> steps) {
		this.id = id;
		this.bean = bean;
		this.chunk = chunk;
		this.steps = steps;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ref")
	public Bean getBean() {
		return this.bean;
	}

	public void setBean(Bean bean) {
		this.bean = bean;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chunk_id")
	public Chunk getChunk() {
		return this.chunk;
	}

	public void setChunk(Chunk chunk) {
		this.chunk = chunk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tasklet")
	public Set<Step> getSteps() {
		return this.steps;
	}

	public void setSteps(Set<Step> steps) {
		this.steps = steps;
	}

}
